### PR TITLE
Support screenshot for crosswalk

### PR DESCRIPTION
**Pull request by fujunwei**

### CODE REVIEW

**Comment by fujunwei** [comment]
@gitawego PTAL, thanks.

**Comment by gitawego** [comment]
there is a conflict of merge, i'm gonna do it asap (when i have time). sorry

**Comment by fujunwei** [comment]
Thanks, done.

**Comment by gitawego** [comment]
thanks for your help :)

**Comment by zarko-tg** [comment]
@fujunwei, @gitawego,

I tested this and the callback of navigator.screenshot.save never executes.

The test environment was:
- current master version of the plugin
- cordova-plugin-crosswalk-webview 1.5.0
- org.xwalk:xwalk_core_library_beta:17.46.448.6
- cordova-android 5.0.0 (or 5.1.0)
- cordova 5.4.1
- Nexus 5 device with Android 6.0.1 on it.

Not using Crosswalk is fine - my test code/app runs as expected and the screenshot image is saved in storage.

**Comment by gitawego** [comment]
@zarko-tg yes, indeed, it doesn't work, because the latest crosswalk plugin with onmessage feature is not yet published. I just tagged version v0.1.4, please use this one. I'm gonna update the code. sorry for this.

**Comment by zarko-tg** [comment]
No rush, I was just experimenting. So now I was about to check against master of cordova-plugin-crosswalk-webview to see cordova-screenshot finally in action but not luck... cordova-plugin-crosswalk-webview has some new (build) issue unrelated to your own plugin. Will get back here as soon as things stabilize again.

Thanks

**Comment by fujunwei** [comment]
You need to wait Crosswalk-18 to release or try it manually following below steps.

The master branch of crosswalk plugin is based on crosswalk-18 that is canary version, you can get it from https://download.01.org/crosswalk/releases/crosswalk/android/canary/18.46.471.0/crosswalk-18.46.471.0.aar, and then install it in local maven
```
mvn install:install-file -DgroupId=org.xwalk -DartifactId=xwalk_core_library_canary \
      -Dversion=18.46.471.0 -Dpackaging=aar  -Dfile=crosswalk-18.46.471.0.aar \
      -DgeneratePom=true
```
Modify config.xml to use the canary AAR
```
<preference name="xwalkVersion" value="org.xwalk:xwalk_core_library_canary:18.46.470.0" />
```
Add mavenLocal() to **-xwalk.gradle file
```
repositories {
  maven {
    url 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2'
  }
  mavenLocal()
}
```
You can also track this issue https://crosswalk-project.org/jira/browse/XWALK-2233, thanks.

**Comment by zarko-tg** [comment]
I can confirm that it works now that Crosswalk 18 has been released in their beta channel.

**Pull request merged**
